# Carga por defecto de las integraciones. No eliminar.
 default_config:
 # Temas personalizados
 frontend:
 themes: !include_dir_merge_named themes
 # Inclusion de modulos externos
 automation: !include automations.yaml
 script: !include scripts.yaml
 scene: !include scenes.yaml
 mqtt: !include mqtt.yaml